# Generated by Django 5.0.6 on 2024-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('text', models.TextField(null=True)),
                ('topic_tags', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('success_rate', models.FloatField()),
                ('total_submission', models.IntegerField()),
                ('total_accepted', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('hints', models.TextField(blank=True, null=True)),
                ('similar_questions_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('similar_questions_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coding_problems',
            },
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
